### ISSUE TITLE
Break on npm install

### ISSUE THREAD

**Issue by conilas** [radarlabs/react-native-radar#13]
This seems to be an issue. 

I tried to install using the command listed on the readme section, but after doing npm install react-native-radar i tried react-native link and got the following:

`module.js:471
throw err;
^

Error: Cannot find module 'rxjs/add/operator/map'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object. (C:\projectang\node_modules@angular-devkit\core\src\l
ogger\indent.js:10:1)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
`

**Comment by nickpatrick** [comment]
Hey, I suspect that this issue is caused by `rxjs` or another dependency, not Radar. See https://github.com/angular/angular-cli/issues/9190. Let us know if you find differently.
